server:
  port: 7075

spring:
  application:
    name: bfc-appmgmt
  profiles:
    active: local
    group:
      "local": "common, local"
      "h2": "common, h2"
      "prd": "common, prd"

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${BFC_DB_URL}
    username: ${BFC_DB_USERNAME}
    password: ${BFC_DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:tcp://localhost/~/bfc
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: ${BFC_DB_URL}
    username: ${BFC_DB_USERNAME}
    password: ${BFC_DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver

logging:
  level:
    org.hibernate.SQL: info