spring:
  profiles:
    active: local
  datasource:
    url: ${BFC_DB_URL}
    username: ${BFC_DB_USERNAME}
    password: ${BFC_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace